#! /bin/sh

COLOR_BLACK="\\033[0;30m" # Black - Regular
COLOR_RED="\\033[0;31m" # Red
COLOR_GREEN="\\033[0;32m" # Green
COLOR_YELLOW="\\033[0;33m" # Yellow
COLOR_BLUE="\\033[0;34m" # Blue
COLOR_PURPLE="\\033[0;35m" # Purple
COLOR_CYAN="\\033[0;36m" # Cyan
COLOR_WHITE="\\033[0;37m" # White

cd ../brunch

# copy all the files in .android/vendor in vendor
echo "Build android version"
cp -rf .android/vendor/ vendor/

# build
echo "\n""$COLOR_YELLOW""-------------------------""$COLOR_WHITE""\n"
brunch build -o android
echo "\n""$COLOR_YELLOW""-------------------------""$COLOR_WHITE""\n"

# put back the web version
echo "Replace web files version"
cp -rf .web/vendor/ vendor/


cd ../android