#! /bin/sh

COLOR_BLACK="\\033[0;30m" # Black - Regular
COLOR_RED="\\033[0;31m" # Red
COLOR_GREEN="\\033[0;32m" # Green
COLOR_YELLOW="\\033[0;33m" # Yellow
COLOR_BLUE="\\033[0;34m" # Blue
COLOR_PURPLE="\\033[0;35m" # Purple
COLOR_CYAN="\\033[0;36m" # Cyan
COLOR_WHITE="\\033[0;37m" # White

cd ..

echo "Cleaning brunch/android/"
rm -rf brunch/android/
mkdir brunch/android/

# create a bin dir in brunch
echo "\n""$COLOR_YELLOW""-------------------------""$COLOR_WHITE""\n"

# copy all the files in .android/vendor in vendor
cp -rf brunch/.android/vendor/ brunch/vendor/

# build
echo "\n""$COLOR_YELLOW""-------------------------""$COLOR_WHITE""\n"
brunch build brunch
echo "\n""$COLOR_YELLOW""-------------------------""$COLOR_WHITE""\n"

# copy the build dir in the assets dir
cp -rf brunch/build/ android/assets/www/

# put back the web version
cp -rf brunch/.web/vendor/ brunch/vendor/

# rebuild
echo "\n""$COLOR_YELLOW""-------------------------""$COLOR_WHITE""\n"
brunch build brunch
echo "\n""$COLOR_YELLOW""-------------------------""$COLOR_WHITE""\n"

cd android