#! /bin/sh

cd ../brunch

# copy all the files in .android/vendor in vendor
echo "Build android version"
cp -rf .android/vendor/ vendor/

# build
echo "\n"
brunch build -o android
echo "\n"

# put back the web version
echo "Replace web files version"
cp -rf .web/vendor/ vendor/

# come back to android folder
cd ../android

echo "Cleaning assets/www"
# delete wwww
rm -rf assets/www/
# create www
mkdir assets/www/

if [ ! "../brunch/android/" = false ]; then
	echo "Updating assets/www"
	# copy all files in assets/www
	cp -r ../brunch/android/* assets/www/
fi