dependencies:
  - phonegap-1.3.0.js
  - ConsoleDummy.js
  - jquery-1.7.1.js
  - underscore-1.1.7.js
  - backbone-0.5.3.js
  - database_wrapper.js
  - persistence/persistence.js
  - persistence/persistence.store.sql.js
  - persistence/persistence.store.memory.js
  - persistence/persistence.store.websql.js
  - persistence/persistence.sync.js
